add RewardForWSOT
ApeX-Protocol/periphery pull request #13
Opened 2022-07-06 10:52 UTC by keeganlee

2022-07-06 13:12 UTC, longdacao approved these changes, later dismissed

2022-07-06 13:16 UTC, riverman123 requested changes
请补充业务逻辑，以方便检查

2022-07-06 13:33 UTC, keeganlee commented
> 请补充业务逻辑，以方便检查

需求是给WSOT活动的100个winner分别奖励一个NFT

2022-07-07 01:30 UTC, riverman123 approved these changes

2022-07-11 02:25 UTC, merged